# use-todo-workflow.yaml
name: Use TODO to ISSUE Workflow

# いつ実行するか設定～
on:
  # ブランチにpushされたときに実行
  push:
    branches: [main, dev, develop]
  # 手動で実行することもできる設定
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: "The SHA of the commit to get the diff for"
        required: true
      MANUAL_BASE_REF:
        description: "By default, the commit entered above is compared to the one directly before it; to go back further, enter an earlier SHA here"
        required: false

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          INSERT_ISSUE_URLS: "true"
      - name: Set Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push Changes
        run: |
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD || echo "main")
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "Automatically added GitHub issue links to TODOs"
            git push origin $CURRENT_BRANCH
          else
            echo "No changes to commit"
          fi
