# use-todo-workflow.yaml
name: Use TODO Workflow

# いつ実行するか設定～
on:
  # ブランチにpushされたときに実行
  push:
    branches: [main, dev, develop]
  # 手動で実行することもできる設定
  workflow_dispatch:

jobs:
  # ここで再利用可能ワークフローを呼び出すよ～
  run-todo-pipeline:
    # 👇 ここ超重要！組織名とリポジトリ名とファイルパス、そしてブランチ名を指定
    uses: stylebikeweb/github-workflows/.github/workflows/todo-to-PR-pipeline.yaml@main
    # 必要なパラメータ渡せるよ～（全部デフォルト値あるから省略もOK！）
    with:
      CLOSE_ISSUES: true
      AUTO_ASSIGN: true
      COMMIT_MESSAGE: "✨ TODOコメントにIssue URLを自動追加したよ～"
      PR_TITLE: "✨ TODO管理を自動化したよ～"
    # 必要な権限を渡す設定
    secrets:
      # GITHUBトークンをPATに変更
      CUSTOM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
